version: "3.9"

services:
  database:
    image: mysql:8.0
    container_name: ${APP_NAME}_database
    command:
      - "sleep inf"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3300:3306
  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: ${APP_NAME}_php
    volumes:
      - php_volume:/var/www/symfony/
    networks:
      - symfony_network
    depends_on:
      - database
  react:
    build:
      context: ./docker/react
    container_name: ${APP_NAME}_react
    volumes:
      - react_volume:/app/
    networks:
      - symfony_network
    depends_on:
      - amb
