version: "3.7"

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    container_name: ${APP_NAME}_database
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - database_volume:/var/lib/mysql
      - ./docker/database/:/docker-entrypoint-initdb.d
    ports:
      - "3300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${APP_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"
  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: ${APP_NAME}_php
    volumes:
      - php_volume:/var/www/p2
    depends_on:
      - database
  react:
    command: 'sh -c "while true; do sleep 360; done"'
    build:
      context: ./docker/react
    container_name: ${APP_NAME}_react
    volumes:
      - react_volume:/app
  nginx:
    build:
      context: ./docker/nginx
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: ${APP_NAME}_nginx
    volumes:
      - php_volume:/var/www/p2
    ports:
      - "8090:80"
    depends_on:
      - php
  ambassador:
    image: quay.io/datawire/ambassador:1.13.0
    container_name: ${APP_NAME}_ambassador
    platform: linux/amd64
    volumes:
      - ./docker/ambassador-config:/ambassador/ambassador-config
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
      - react
volumes:
  database_volume:
  react_volume:
  php_volume:

